baseURL: "https://talentafigan.github.io/"
title: Figan
theme: PaperMod

# build
buildDrafts: false
buildFuture: false
buildExpired: false

enableGitInfo : true

copyright :  © 2024 Figan

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Portfolio]
  author: Figan
  # author: ["Me", "You"] # multiple authors
  defaultTheme: light # dark, light
  disableThemeToggle: false
  
  homeInfoParams:
    Title: it's Figan 👋
    Content: >
      - I am **Talenta Figan**, a dedicated Software Engineer with over **4 years** of experience in building and maintaining **Web Application, Mobile Application & Dekstop Application**. Skilled in **[Javascript](https://javascript.com), [Dart](https://dart.dev), [React](https://react.dev), [Vue](https://vuejs.org), [Flutter](https://flutter.dev), [Node](https://nodejs.org) & [Express](https://expressjs.com)** and much more. I have a strong track record of delivering high-quality software solutions.

      -

      - I am eager to bring my expertise and enthusiasm to a dynamic organization and contribute to its success.

      -

      - if you kinda like to see [**My Works**](/work).

      -

      - Regards. 🤝

  socialIcons:
    - name: github
      url: "https://www.github.com/talentafigan/"
    - name: linkedin
      url: "https://www.linkedin.com/in/talenta-figan-21364b180/"
    - name: telegram
      url: "https://t.me/talentafigan"


menu:
  main:
    - identifier: work
      name: Works
      url: /work/
      weight: 10 