baseURL: "https://talentafigan.github.io/"
title: Figan
theme: PaperMod

# build
buildDrafts: false
buildFuture: false
buildExpired: false

enableGitInfo : true

copyright :  © 2024 Figan

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Portfolio]
  author: Figan
  # author: ["Me", "You"] # multiple authors
  defaultTheme: light # dark, light
  disableThemeToggle: false
  
  homeInfoParams:
    Title: it's Figan 👋
    Content: >
      -

      my name is **talenta maulana figan** and i am a self-taught **software engineer**.

      - I love expressing creativity into the masterpiece of technology or lines of code that benefit everyone.

      -

      - if you kinda like to see [**My Works**](/cv/#professional-projects).

      -

      - Regards.


  socialIcons:
    - name: github
      url: "https://www.github.com/talentafigan/"
    - name: linkedin
      url: "https://www.linkedin.com/in/talenta-figan-21364b180/"


menu:
  main:
    - identifier: about
      name: Profile Summary
      url: /cv/
      weight: 10 